
title: Othman El Hammouchi
email: contact@othmanelhammouchi.com
description: >-
  A master's student's journey through the world of applied and financial mathematics.
baseurl: ""
url: "https://othmanelhammouchi.com/"
github_username:  OthmanElHammouchi
linkedin_username: othman-el-hammouchi

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
