baseURL = 'https://othmanelhammouchi.com/'
languageCode = 'en-us'
title = 'Othman El Hammouchi'
theme = "hugo-coder"

enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[markup.goldmark.renderer]
  unsafe = true

[security]
  enableInlineShortcodes = true

[params]
  author = "Othman El Hammouchi"
  description = "Personal Website"
  keywords = "blog,developer,data science,personal"
  info = ["Mathematics", "Data Science", "QuantFin"]
  avatarURL = "images/avatar.png"
  #gravatar = "john.doe@example.com"
  dateFormat = "January 2, 2006"
  since = 2022

  favicon_16 = "images/favicon-16.png"
  favicon_32 = "images/favicon-32.png"
  favicon_SVG = "images/favicon.svg"

  # Right To Left, shift content direction for languagues such as Arabic
  rtl = false

  math = false                  # disable KaTeX, we use MathJax
  colorScheme = "auto"
  hideColorSchemeToggle = false

  # Series see also post count
  maxSeeAlsoItems = 5
  maxFrontPagePosts = 3

  # Custom CSS
  customCSS = ["css/custom.css"]

  # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
  customSCSS = []

  # Custom JS
  customJS = ["js/plyr.js", "js/mathjax-config.js"]

  # Custom remote JS files
  customRemoteJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/OthmanElHammouchi/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/othman-el-hammouchi/"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"

[[languages.en.menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[languages.en.menu.main]]
  name = "Contact me"
  weight = 3
  url = "contact/"
